enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const Gap = SpriteKind.create()
}
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy = -100
    animation.setAction(mySprite, ActionKind.Jumping)
    mySprite.startEffect(effects.coolRadial, 300)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Gap, function (sprite, otherSprite) {
    if (otherSprite.right - sprite.left < 2) {
        info.changeScoreBy(1)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false)
})
let projectile: Sprite = null
let gapSprite: Sprite = null
let gapImage: Image = null
let bottomImage: Image = null
let topImage: Image = null
let gap = 0
let mySprite: Sprite = null
scene.setBackgroundImage(assets.image`myImage`)
info.setScore(0)
effects.blizzard.startScreenEffect()
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 d f . . 
    . . . . b 5 5 1 f f 5 d 4 c . . 
    . . . . b 5 5 d f b d d 4 2 4 . 
    b 5 5 5 b b d 5 5 5 4 4 4 2 2 b 
    b b 5 5 5 5 b 5 5 4 4 4 4 2 b . 
    b 5 c 5 5 5 5 d 5 5 5 5 5 b . . 
    c 5 5 c 5 5 5 b 5 5 5 5 5 5 b . 
    c b 5 5 c c b 5 5 5 5 5 5 5 b . 
    . c 5 5 5 5 5 5 5 5 5 5 5 d b . 
    . . c b 5 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, SpriteKind.Player)
mySprite.ay = 300
let anim = animation.createAnimation(ActionKind.Jumping, 25)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . b b b b 5 5 5 5 5 5 5 b . . 
    . b 5 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b 5 5 5 b 1 f f 5 4 4 2 4 . 
    . b 5 b 5 5 5 d f b 5 4 4 4 2 . 
    b 5 5 c d 5 5 b 5 5 5 4 4 4 4 b 
    b 5 5 5 c c b 5 5 5 4 5 5 5 b . 
    . b 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    . c 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    . . c b 5 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b 5 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 5 1 f 5 d 5 f . . 
    . . b 5 5 5 b 1 f f 5 4 4 c . . 
    . b 5 b 5 5 5 d f b 4 4 4 4 2 b 
    b 5 5 c 5 5 5 b 5 5 4 4 4 4 b . 
    c 5 5 5 c c b 5 5 5 5 5 5 5 b . 
    c b 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    . c 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    . . c b 5 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 5 f . . 
    . . . . b 5 5 1 f f 5 5 5 c . . 
    . . . . b 5 5 d f b 5 5 4 4 . . 
    b 5 5 5 b b 5 5 5 5 5 4 4 4 4 2 
    b b 5 5 5 5 b 5 5 5 4 4 4 4 b . 
    b 5 c 5 5 5 5 5 5 5 5 5 5 b . . 
    c 5 5 c 5 5 5 b 5 5 5 5 5 5 b . 
    c b 5 5 c c b 5 5 5 5 5 5 5 b . 
    . c 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    . . c b 5 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 5 c . . 
    . . . . b 5 5 1 f f 5 5 4 4 4 b 
    . . . . b 5 5 d f b 5 4 4 4 b . 
    . . . b 5 5 5 5 5 5 4 4 4 b . . 
    . . b 5 5 5 5 5 5 5 5 5 5 b . . 
    . b 5 5 5 5 5 5 5 5 5 5 5 5 b . 
    b 5 5 5 b b b 5 5 5 5 5 5 5 b . 
    b 5 5 b 5 5 5 c 5 5 5 5 5 5 b . 
    . b b 5 5 5 c 5 5 5 5 5 5 5 b . 
    . b 5 5 b c 5 5 5 5 5 5 5 5 b . 
    . b c c c 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 5 c . . 
    . . . . b 5 5 1 f f 5 5 4 4 4 b 
    . . . . b 5 5 d f b 5 4 4 4 b . 
    . . . b 5 5 5 5 5 5 4 4 4 b . . 
    . b b 5 5 5 5 5 5 5 5 5 5 b . . 
    b 5 5 5 b b b 5 5 5 5 5 5 5 b . 
    b 5 5 b 5 5 d c 5 5 5 5 5 5 b . 
    . b b d 5 d c 5 5 5 5 5 5 5 b . 
    . b 5 5 b c 5 5 5 5 5 5 5 5 b . 
    . . c c c 5 5 5 5 5 5 5 5 5 b . 
    . . . . c c 5 5 5 5 5 5 b b . . 
    . . . . . . c c c c c b b . . . 
    `)
anim.addAnimationFrame(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 5 f . . 
    . . . . b 5 5 1 f f 5 5 4 c . . 
    . . . . b 5 5 d f b 5 5 4 4 . . 
    . b b b 5 5 5 5 5 5 4 4 4 4 4 b 
    b 5 5 5 b b 5 5 5 4 4 4 4 4 b . 
    b b 5 5 5 5 b 5 5 5 5 5 5 b . . 
    b 5 c 5 5 5 5 5 5 5 5 5 5 5 b . 
    b 5 5 c 5 5 5 b 5 5 5 5 5 5 b . 
    . c 5 5 c c b 5 5 5 5 5 5 5 b . 
    . . c b 5 5 5 5 5 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    . . . . . . . . . . . . . . . . 
    `)
animation.attachAnimation(mySprite, anim)
game.onUpdate(function () {
    if (mySprite.vy > 0) {
        animation.setAction(mySprite, ActionKind.Idle)
    }
    if (mySprite.bottom > 120 || mySprite.top < 0) {
        game.over(false)
    }
})
game.onUpdateInterval(1500, function () {
    gap = randint(0, 3)
    if (gap == 0) {
        topImage = img`
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......beeeeeeeeeeb......
            .......beeeeeeeeb.......
            ........beeeeeeb........
            `
        bottomImage = img`
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....bdbbdbbbbdbbdb.....
            .....bbdbbddddbbdbb.....
            .....ebbddbbbbddbbe.....
            .....eebbbddddbbbee.....
            .....eeeebbbbbbeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            `
    } else if (gap == 1) {
        topImage = img`
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            .......eeeeeeeeee.......
            ........eeeeeeee........
            ........................
            ........................
            ........................
            `
        bottomImage = img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....bdbbdbbbbdbbdb.....
            .....bbdbbddddbbdbb.....
            .....ebbddbbbbddbbe.....
            .....eebbbddddbbbee.....
            .....eeeebbbbbbeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            `
    } else if (gap == 2) {
        topImage = img`
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .......eeeeeeeeee.......
            ........eeeeeeee........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `
        bottomImage = img`
            ........................
            ........................
            ........................
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....bdbbdbbbbdbbdb.....
            .....bbdbbddddbbdbb.....
            .....ebbddbbbbddbbe.....
            .....eebbbddddbbbee.....
            .....eeeebbbbbbeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            `
    } else {
        topImage = img`
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            ......eeeeeeeeeeee......
            .......eeeeeeeeee.......
            ........eeeeeeee........
            ........................
            `
        bottomImage = img`
            ........................
            ..........bbbb..........
            ........bbddddbb........
            .......bddbbbbddb.......
            ......bdbbddddbbdb......
            .....bdbbdbbbbdbbdb.....
            .....bdbdbddddbdbdb.....
            .....bdbbdbbbbdbbdb.....
            .....bbdbbddddbbdbb.....
            .....ebbddbbbbddbbe.....
            .....eebbbddddbbbee.....
            .....eeeebbbbbbeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            .....eeeeeeeeeeeeee.....
            `
    }
    gapImage = image.create(2, scene.screenHeight())
    gapImage.fill(1)
    gapSprite = sprites.create(gapImage, SpriteKind.Gap)
    gapSprite.setFlag(SpriteFlag.AutoDestroy, true)
    gapSprite.setFlag(SpriteFlag.Invisible, true)
    gapSprite.left = scene.screenWidth()
    gapSprite.vx = -45
    projectile = sprites.createProjectileFromSide(topImage, -45, 0)
    projectile.top = 0
    projectile = sprites.createProjectileFromSide(bottomImage, -45, 0)
    projectile.bottom = scene.screenHeight()
})
